import Head from 'next/head'
import Image from 'next/image'
import { signOut, useSession } from 'next-auth/react'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { doc, getDoc } from 'firebase/firestore'
import { db } from '../firebase'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Chat from '../components/Chat'
import Footer from '../components/Footer'

export default function Home() {
  const router = useRouter()
  const { data: session } = useSession()
  useEffect(() => {
    if (!session) {
      router.push('/login')
    }
    else {
      localStorage.setItem('healthcare', JSON.stringify(session))
      handleSignUp()
    }
  }, [])


  const handleSignUp = async () => {
    const docRef = doc(db, 'users', session?.user?.email)
    const docSnap = await getDoc(docRef)
    if (docSnap.exists()) {
      console.log('Document Data', docSnap.data())
    }
    else {
      router.push({
        pathname: "/signup",
        query: { session }
      })
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Footer />
      <Chat />

      <main>
        <p>{session?.user?.name}</p>
        <button onClick={() => signOut()}>Sign Out</button>
      </main>
    </div>

  )
}
